cmake_minimum_required(VERSION 3.15)

option(BUILD_AENET "Build aenet targets" OFF)

if(NOT BUILD_AENET)
  message(STATUS "==============================================================================")
  message(STATUS "Build aenet with CMake")
  message(STATUS "==============================================================================")
  message(STATUS "To build:  cmake -S . -B build -DBUILD_AENET=ON && cmake --build build --target build_all")
  message(STATUS "Or pick a different target: main | lib | tools | build_tests | test")
  message(STATUS "")
  message(STATUS "The following options are available to configure the build:")
  message(STATUS "")
  message(STATUS "  -DCMAKE_BUILD_TYPE=Release/Debug  (default: Release)")
  message(STATUS "     Build type.")
  message(STATUS "  -DUSE_MPI=ON/OFF                  (default: OFF)")
  message(STATUS "     Enable MPI parallelization.")
  message(STATUS "  -DUSE_MKL=ON/OFF                  (default: OFF)")
  message(STATUS "     Use Intel MKL for BLAS/LAPACK.")
  message(STATUS "  -DUSE_OPENBLAS=ON/OFF             (default: OFF)")
  message(STATUS "     Use OpenBLAS for BLAS/LAPACK.")
  message(STATUS "  -DCMAKE_Fortran_COMPILER=<path>   (e.g., ifort, gfortran)")
  message(STATUS "     Specify the Fortran compiler.")
  message(STATUS "")
  message(STATUS "Example: cmake .. -DBUILD_AENET=ON -DUSE_MPI=ON -DCMAKE_BUILD_TYPE=Debug")
  message(STATUS "")
  message(STATUS "The following custom targets are available:")
  message(STATUS "")
  message(STATUS "  make main         (Builds generate.x, train.x, predict.x)")
  message(STATUS "  make lib          (Builds aenet static and shared libraries)")
  message(STATUS "  make tools        (Builds all tool executables)")
  message(STATUS "  make build_all    (Builds all executables, libraries, and tests)")
  message(STATUS "  make build_tests  (Builds all unit test executables)")
  message(STATUS "  make test         (Runs the unit tests)")
  message(STATUS "")
endif()

if(BUILD_AENET)
  project(AENET Fortran)
  set(AENET_SUPERBUILD ON)
  include(CTest)
  add_subdirectory(src)
endif()
