#+AUTHOR: Nongnuch Artrith
#+TITLE: Input file format for =generate.x=

* Alphabetic list of keywords

  All keywords are case insensitive and independent of the order.  Blank
  lines and lines starting with =!=, =#=, or =%= are ignored.

  - =debug= (optional) :: Activate debugging mode; additional output will
       be generated.
  - =files= (required) :: Specifies number of and path to reference
       structures in the *ænet* XSF format.  The first line following
       the keyword contains the number =<NF>= of structure files.  Each
       of the =<NF>= following lines contains a file system path.
  - =output= (optional) :: Defines the path to the training set file
       that is going to be generated.  The default name is
       "refdata.train".  Note that the training set file is in a binary
       format and cannot be viewed by a text editor.  Depending on the
       number of reference structures, the file can become very large
       (e.g., 1 GB).
  - =setups= (required) :: Specifies paths to structural fingerprint basis
       function setup files.  Each of the =<NT>= lines following the
       keyword contains the chemical symbol =<T_i>= and the path to the
       setup file for one species.
  - =timing= (optional) :: Activate timing; additional output files will
       be created.
  - =types= (required) :: Defines the number of atomic species, their
       names, and atomic energies.  The first line after the keyword
       contains the number of different species =<NT>=; the following
       =<NT>= lines each contain the chemical symbol =<T_i>= and atomic
       energy =<E_atom-i>= of one species.

* Input file template (generate.in)

#+BEGIN_EXAMPLE
OUTPUT  <path/to/output/file>

TYPES
<NT>
<T_1>   <E_atom-1>
<T_2>   <E_atom-2>
...
<T_NT>  <E_atom-NT>

SETUPS
<T_1>   <path/to/setup-1>
<T_2>   <path/to/setup-2>
...
<T_NT>  <path/to/setup-NT>

FILES
<NF>
<path/to/file-1.xsf>
<path/to/file-2.xsf>
...
<path/to/file-NF.xsf>
#+END_EXAMPLE

* Input file example (generate.in) for TiO_{2}

The atomic energies defined in the =TYPES= section is subtracted from the
total energy before the potential training to reduce the fluctuations in
the fitted energy (the target energy).  Two different approaches towards
selecting the atomic energies are shown below: In [[http://dx.doi.org/10.1016/j.commatsci.2015.11.047][ /Comput. Mater. Sci./
*114* (2016) 135-150]] the atomic energies are chosen to be the energies of
isolated atoms.  With this choice, the trained energy (total energy
minus atomic energies) corresponds to the /cohesive energy/, which is
reported by ænet's =predict.x= tool.

#+BEGIN_EXAMPLE
OUTPUT  TiO2.train

TYPES
2
O   -432.503149303  ! eV
Ti -1604.604515075  ! eV

SETUPS
O   O.fingerprint.stp
Ti Ti.fingerprint.stp

FILES
7815
./structures/0001.xsf
./structures/0002.xsf
...
./structures/7815.xsf
#+END_EXAMPLE

Alternatively, the atomic energies can be set to the average atomic
energy of all structures in the reference data set to minimize the range
of the target energy (e.g., [[http://dx.doi.org/10.1103/PhysRevB.96.014112][/Phys. Rev. B/ *96*, 2017, 014112]]).  The
downside of this approach is that the energy difference is no longer
interpretable, i.e., it does not correspond to the cohesive energy.

#+BEGIN_EXAMPLE
OUTPUT TiO.train

TYPES
2
O   -433.23448532  | eV
Ti -1626.66972707  | eV

SETUPS
O   O.fingerprint.stp
Ti Ti.fingerprint.stp

FILES
7815
./structures/0001.xsf
./structures/0002.xsf
...
./structures/7815.xsf
#+END_EXAMPLE
