#-*- mode: makefile -*-
#-----------------------------------------------------------------------
#                GNU Fortran Compiler (serial) on MacOS
#-----------------------------------------------------------------------
#+ This file is part of the AENET package.
#+
#+ Copyright (C) 2012-2019 Nongnuch Artrith and Alexander Urban
#+
#+ This Source Code Form is subject to the terms of the Mozilla Public
#+ License, v. 2.0. If a copy of the MPL was not distributed with this
#+ file, You can obtain one at http://mozilla.org/MPL/2.0/.
#+
#+ This program is distributed in the hope that it will be useful, but
#+ WITHOUT ANY WARRANTY; without even the implied warranty of
#+ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#+ Mozilla Public License, v. 2.0, for more details.
#+ ---------------------------------------------------------------------
#+ If you make use of AENET for your publication, please cite:
#+ [1] N. Artrith and A. Urban, Comput. Mater. Sci. 114 (2016) 135-150.
#+ [2] J. Behler and M. Parrinello, Phys. Rev. Lett. 98 (2007) 146401.
#+
#+ If you used the Chebyshev descriptor, please cite:
#+ [3] N. Artrith, A. Urban, and G. Ceder, PRB 96 (2017) 014112.
#-----------------------------------------------------------------------
# 2025-04-06 AU -- adapted to current MacOS Sequoia
# 2015-05-26 Alexander Urban (AU) and Nongnuch Artrith (NA)
#-----------------------------------------------------------------------

SUFFIX   = gfortran_serial

FC       = gfortran -c
LD       = gfortran
DEBUG    =
FCFLAGS  = -O3 -pedantic -fexternal-blas $(DEBUG)
LDFLAGS  = -static-libgfortran $(DEBUG) -framework Accelerate
# LDFLAGS  = -static-libgfortran -static-libquadmath $(DEBUG) -framework Accelerate -Wl,-rpath,/opt/homebrew/opt/gcc/lib/gcc/14
NUMLIB   = -framework Accelerate

CC       = gcc -c
CCFLAGS  =

# linker for C-interoperable library (gcc & gfortran)
LIBLD    = gfortran
LIBFLAGS = -dynamiclib
LIBLIB   = $(NUMLIB) ../lib/liblbfgsb.dylib

AR       = ar
ARFLAGS  = -crusv

include ./Makefile.inc

lib      : libaenet.a libaenet.dylib

libaenet.dylib : $(PICOBJECTS) Makefile.inc
	$(LIBLD) $(LIBFLAGS) $(PICOBJECTS) $(LIBLIB) -o $@

libaenet.so: libaenet.dylib
	ln -sf libaenet.dylib libaenet.so
